name: rfs express
favicon: null
layout_spectrum: 0.49399
typography_spectrum: 0.25344
title: rfs express
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c60000'
    - '#91f3ff'
    - '#0ca7c1'
    - '#fffb5c'
    - '#f2f100'
  brandStrength: 0.36977633764036
  lightness: 0.09275839733891189
  saturation: 0.5316935030277818
  rhythmicContrast: 0.4413805252406746
purpose: []
